export const BLOCKS = {
  monAM: {
    order: 1,
    groups: ['studentSession'],
    rooms: ['room1'],
    time: '11am-12:30pm Eastern Time',
    date: 'Monday, July 20',
  },
  monAft: {
    order: 2,
    groups: ['studentSession'],
    rooms: ['room1'],
    time: '1pm-2:30pm Eastern Time',
    date: 'Monday, July 20',
  },
  monEve: {
    order: 3,
    groups: ['studentSession'],
    rooms: ['room1'],
    time: '3pm-4:30pm Eastern Time',
    date: 'Monday, July 20',
  },
  tuesAM: {
    order: 4,
    groups: ['plenary'],
    rooms: ['room1'],
    time: '11am-12:30pm Eastern Time',
    name: 'Tuesday Plenary Session',
    date: 'Tuesday, July 21',
  },
  tuesAft: {
    order: 5,
    groups: ['IEMIT', 'RX', 'RB', 'BSH'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '1pm-2:30pm Eastern Time',
    name: 'Tuesday Session 1',
    date: 'Tuesday, July 21',
  },
  tuesEve: {
    order: 6,
    groups: ['IEMIT', 'RX', 'RB', 'BSH'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '3pm-4:30pm Eastern Time',
    name: 'Tuesday Session 2',
    date: 'Tuesday, July 21',
  },
  wedAM: {
    order: 7,
    groups: ['plenary'],
    rooms: ['room1'],
    time: '11am-12:30pm Eastern Time',
    name: 'Wednesday Plenary Session',
    date: 'Wednesday, July 22',
  },
  wedAft: {
    order: 8,
    groups: ['M3-I2', 'UMEA', 'IMM', 'DIP'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '1pm-2:30pm Eastern Time',
    name: 'Wednesday Session 1',
    date: 'Wednesday, July 22',
  },
  wedEve: {
    order: 9,
    groups: ['M3-I2', 'UMEA', 'IMM', ['IEMIT', 'MMV']],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '3pm-4:30pm Eastern Time',
    name: 'Tuesday Session 2',
    date: 'Wednesday, July 22',
  },
  thursAM: {
    order: 10,
    groups: ['plenary'],
    rooms: ['room1'],
    time: '11am-12:30pm Eastern Time',
    name: 'Thursday Plenary Session',
    date: 'Thursday, July 23',
  },
  thursAft: {
    order: 11,
    groups: ['DAYS', 'DIP', 'CP', 'IHMIC'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '1pm-2:30pm Eastern Time',
    name: 'Thursday Session 1',
    date: 'Thursday, July 23',
  },
  thursEve: {
    order: 12,
    groups: ['DAYS', 'Machine Learning', ['CP', 'IMM'], 'IHMIC'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '3pm-4:30pm Eastern Time',
    name: 'Thursday Session 2',
    date: 'Thursday, July 23',
  },
}
