export const BLOCKS = {
  monAM: {
    order: 1,
    groups: ['Student Session'],
    rooms: ['room1'],
    time: '12:00pm-5:30pm',
    date: 'Monday, July 20',
    name: 'Student Session',
  },
  tuesAM: {
    order: 4,
    groups: ['Plenary'],
    rooms: ['room1'],
    time: '11:00am-12:30pm',
    name: 'Tuesday Plenary Session',
    date: 'Tuesday, July 21',
    slack: 'gemworkshop.slack.com/messages/1-plenary-tuesday',
  },
  tuesAft: {
    order: 5,
    groups: ['IEMIT', 'RX', 'RB', 'BSH'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '1:00pm-2:30pm',
    name: 'Tuesday Concurrent Session 1',
    date: 'Tuesday, July 21',
  },
  tuesEve: {
    order: 6,
    groups: ['IEMIT', 'RX', 'RB', 'BSH'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '3:00pm-4:30pm',
    name: 'Tuesday Concurrent Session 2',
    date: 'Tuesday, July 21',
  },
  tuesPM: {
    order: 7,
    groups: [],
    rooms: ['room1'],
    time: '5:00pm-7:00pm',
    name: 'Poster Session 1',
    date: 'Tuesday, July 21',
  },

  wedAM: {
    order: 7,
    groups: ['plenary'],
    rooms: ['room1'],
    time: '11:00am-12:30pm',
    name: 'Wednesday Plenary Session',
    date: 'Wednesday, July 22',
    slack: 'gemworkshop.slack.com/messages/1-plenary-wednesday',
  },
  wedAft: {
    order: 8,
    groups: ['M3-I2', 'UMEA', 'IMM', 'DIP'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '1:00pm-2:30pm',
    name: 'Wednesday Concurrent Session 1',
    date: 'Wednesday, July 22',
  },
  wedEve: {
    order: 9,
    groups: ['M3-I2', 'UMEA', 'IMM', ['IEMIT', 'MMV']],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '3:00pm-4:30pm',
    name: 'Wednesday Concurrent Session 2',
    date: 'Wednesday, July 22',
    slack: 'gemworkshop.slack.com/messages/0-decadal-future-and-beyond',
  },
  wedPM: {
    order: 7,
    groups: [],
    rooms: ['room1'],
    time: '5:00pm-7:00pm',
    name: 'Discussion: Decadal Future and Beyond!',
    date: 'Wednesday, July 22',
  },

  thursAM: {
    order: 10,
    groups: ['plenary'],
    rooms: ['room1'],
    time: '11:00am-12:30pm',
    name: 'Thursday Plenary Session',
    date: 'Thursday, July 23',
    slack: 'gemworkshop.slack.com/messages/1-plenary-thursday',
  },
  thursAft: {
    order: 11,
    groups: ['DAYS', 'DIP', 'CP', 'IHMIC'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '1:00pm-2:30pm',
    name: 'Thursday Concurrent Session 1',
    date: 'Thursday, July 23',
  },
  thursEve: {
    order: 12,
    groups: ['DAYS', 'ML', ['CP', 'IMM'], 'IHMIC'],
    rooms: ['room2', 'room3', 'room4', 'room5'],
    time: '3:00pm-4:30pm',
    name: 'Thursday Concurrent Session 2',
    date: 'Thursday, July 23',
  },
  thursPM: {
    order: 7,
    groups: [],
    rooms: ['room1'],
    time: '5:00pm-7:00pm',
    name: 'Poster Session 2',
    date: 'Tuesday, July 21',
  },
}
