export const BLOCKS = {
  monAM: {
    order: 1,
    groups: ['Student Session'],
    rooms: ['room1'],
    time: '12:00pm-5:30pm',
    date: 'Monday, July 20',
    name: 'Student Session',
    slack: 'gemworkshop.slack.com/messages/0-student',
    done: true,
    vidUrls: ['/student/video'],
  },
  tuesAM: {
    order: 4,
    groups: ['Plenary'],
    time: '11:00am-12:30pm',
    name: 'Tuesday Plenary Session',
    date: 'Tuesday, July 21',
    slack: 'gemworkshop.slack.com/messages/1-plenary-tuesday',
    day: 'tuesday',
    rooms: ['plen1'],
    done: true,
    vidUrls: ['/plenary/video'],
  },
  tuesAft: {
    order: 5,
    groups: ['IEMIT', 'RX', 'RB', 'BSH'],
    rooms: ['room1', 'room2', 'room3', 'room4'],
    time: '1:00pm-2:30pm',
    name: 'Tuesday Concurrent Session 1',
    date: 'Tuesday, July 21',
    done: true,
  },
  tuesEve: {
    order: 6,
    groups: ['IEMIT', 'RX', 'RB', 'BSH'],
    rooms: ['room1', 'room2', 'room3', 'room4'],
    time: '3:00pm-4:30pm',
    name: 'Tuesday Concurrent Session 2',
    date: 'Tuesday, July 21',
    done: true,
  },
  tuesPM: {
    order: 7,
    groups: [],
    rooms: [],
    time: '5:00pm-7:00pm',
    name: 'Poster Session 1',
    date: 'Tuesday, July 21',
    link: '/posters/day/tuesday',
  },

  wedAM: {
    order: 7,
    groups: ['plenary'],
    time: '11:00am-12:30pm',
    name: 'Wednesday Plenary Session',
    date: 'Wednesday, July 22',
    slack: 'gemworkshop.slack.com/messages/1-plenary-wednesday',
    day: 'wednesday',
    rooms: ['plen2'],
    done: true,
  },
  wedAft: {
    order: 8,
    groups: ['M3-I2', 'UMEA', 'IMM', 'DIP'],
    rooms: ['room1', 'room2', 'room3', 'room4'],
    time: '1:00pm-2:30pm',
    name: 'Wednesday Concurrent Session 1',
    date: 'Wednesday, July 22',
    done: true,
  },
  wedEve: {
    order: 9,
    groups: ['M3-I2', 'UMEA', 'IMM', ['IEMIT', 'MMV']],
    rooms: ['room1', 'room2', 'room3', 'room5'],
    time: '3:00pm-4:30pm',
    name: 'Wednesday Concurrent Session 2',
    date: 'Wednesday, July 22',
    slack: 'gemworkshop.slack.com/messages/0-decadal-future-and-beyond',
    done: false,
  },
  wedPM: {
    order: 7,
    groups: [],
    rooms: ['room4'],
    time: '5:00pm-7:00pm',
    name: 'Discussion: Decadal Future and Beyond!',
    date: 'Wednesday, July 22',
    done: false,
  },

  thursAM: {
    order: 10,
    groups: ['plenary'],
    time: '11:00am-12:30pm',
    name: 'Thursday Plenary Session',
    date: 'Thursday, July 23',
    slack: 'gemworkshop.slack.com/messages/1-plenary-thursday',
    day: 'thursday',
    rooms: ['plen3'],
    done: false,
  },
  thursAft: {
    order: 11,
    groups: ['DAYS', 'DIP', 'CP', 'IHMIC'],
    rooms: ['room1', 'room2', 'room3', 'room4'],
    time: '1:00pm-2:30pm',
    name: 'Thursday Concurrent Session 1',
    date: 'Thursday, July 23',
    done: false,
  },
  thursEve: {
    order: 12,
    groups: ['DAYS', 'ML', ['CP', 'IMM'], 'IHMIC'],
    rooms: ['room1', 'room5', 'room3', 'room4'],
    time: '3:00pm-4:30pm',
    name: 'Thursday Concurrent Session 2',
    date: 'Thursday, July 23',
    done: false,
  },
  thursPM: {
    order: 7,
    groups: [],
    rooms: [],
    time: '5:00pm-7:00pm',
    name: 'Poster Session 2',
    date: 'Thursday, July 23',
    link: '/posters/day/thursday',
    done: false,
  },
  thursPPM: {
    groups: ['Sam Bingham Memorial'],
    rooms: ['room1'],
    time: '7:00pm-9:00pm',
    name: 'Sam Bingham Memorial',
    slack: 'gemworkshop.slack.com/messages/0-support-each-other',
    done: false,
  },
}
