export const LANDING = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const HOME = '/home'
export const ADMIN = '/admin'
export const SCHEDULE = '/schedule'
export const FOCUSGROUPS = '/focusgroups'
export const ONEFOCUSGROUP = '/focusgroups/:focusId'
